// <auto-generated />
using System;
using Exams_App_C__.Net_Server.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exams_App_C__.Net_Server.Migrations
{
    [DbContext(typeof(ExamsDbContext))]
    [Migration("20240404140456_v22")]
    partial class v22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnswerDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("AnswerNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = "a-101",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6192),
                            IsCorrect = false,
                            QuestionId = "q-1"
                        },
                        new
                        {
                            Id = "a-2",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6286),
                            IsCorrect = true,
                            QuestionId = "q-1"
                        },
                        new
                        {
                            Id = "a-3",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6290),
                            IsCorrect = false,
                            QuestionId = "q-1"
                        },
                        new
                        {
                            Id = "a-4",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6302),
                            IsCorrect = false,
                            QuestionId = "q-1"
                        },
                        new
                        {
                            Id = "a-21",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6312),
                            IsCorrect = false,
                            QuestionId = "q-2"
                        },
                        new
                        {
                            Id = "a-22",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6331),
                            IsCorrect = false,
                            QuestionId = "q-2"
                        },
                        new
                        {
                            Id = "a-23",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6335),
                            IsCorrect = true,
                            QuestionId = "q-2"
                        },
                        new
                        {
                            Id = "a-24",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6338),
                            IsCorrect = false,
                            QuestionId = "q-2"
                        },
                        new
                        {
                            Id = "a-31",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6345),
                            IsCorrect = false,
                            QuestionId = "q-3"
                        },
                        new
                        {
                            Id = "a-32",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6397),
                            IsCorrect = false,
                            QuestionId = "q-3"
                        },
                        new
                        {
                            Id = "a-33",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6401),
                            IsCorrect = false,
                            QuestionId = "q-3"
                        },
                        new
                        {
                            Id = "a-34",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6405),
                            IsCorrect = true,
                            QuestionId = "q-3"
                        },
                        new
                        {
                            Id = "a-41",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6423),
                            IsCorrect = true,
                            QuestionId = "q-4"
                        },
                        new
                        {
                            Id = "a-42",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6458),
                            IsCorrect = false,
                            QuestionId = "q-4"
                        },
                        new
                        {
                            Id = "a-43",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6462),
                            IsCorrect = false,
                            QuestionId = "q-4"
                        },
                        new
                        {
                            Id = "a-44",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6466),
                            IsCorrect = false,
                            QuestionId = "q-4"
                        },
                        new
                        {
                            Id = "a-51",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6469),
                            IsCorrect = true,
                            QuestionId = "q-5"
                        },
                        new
                        {
                            Id = "a-52",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6473),
                            IsCorrect = false,
                            QuestionId = "q-5"
                        },
                        new
                        {
                            Id = "a-53",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6477),
                            IsCorrect = false,
                            QuestionId = "q-5"
                        },
                        new
                        {
                            Id = "a-54",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6481),
                            IsCorrect = false,
                            QuestionId = "q-5"
                        },
                        new
                        {
                            Id = "a-61",
                            AnswerDescription = "Paris",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6484),
                            IsCorrect = true,
                            QuestionId = "q-6"
                        },
                        new
                        {
                            Id = "a-62",
                            AnswerDescription = "London",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6490),
                            IsCorrect = false,
                            QuestionId = "q-6"
                        },
                        new
                        {
                            Id = "a-63",
                            AnswerDescription = "Berlin",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6493),
                            IsCorrect = false,
                            QuestionId = "q-6"
                        },
                        new
                        {
                            Id = "a-64",
                            AnswerDescription = "Rome",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6496),
                            IsCorrect = false,
                            QuestionId = "q-6"
                        },
                        new
                        {
                            Id = "a-71",
                            AnswerDescription = "Pacific Ocean",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6503),
                            IsCorrect = true,
                            QuestionId = "q-7"
                        },
                        new
                        {
                            Id = "a-72",
                            AnswerDescription = "Atlantic Ocean",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6507),
                            IsCorrect = false,
                            QuestionId = "q-7"
                        },
                        new
                        {
                            Id = "a-73",
                            AnswerDescription = "Indian Ocean",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6524),
                            IsCorrect = false,
                            QuestionId = "q-7"
                        },
                        new
                        {
                            Id = "a-74",
                            AnswerDescription = "Arctic Ocean",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6566),
                            IsCorrect = false,
                            QuestionId = "q-7"
                        },
                        new
                        {
                            Id = "a-81",
                            AnswerDescription = "Mercury",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6623),
                            IsCorrect = true,
                            QuestionId = "q-8"
                        },
                        new
                        {
                            Id = "a-82",
                            AnswerDescription = "Atlantic Ocean",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6631),
                            IsCorrect = false,
                            QuestionId = "q-8"
                        },
                        new
                        {
                            Id = "a-83",
                            AnswerDescription = "Indian Ocean",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6635),
                            IsCorrect = false,
                            QuestionId = "q-8"
                        },
                        new
                        {
                            Id = "a-84",
                            AnswerDescription = "Arctic Ocean",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6639),
                            IsCorrect = false,
                            QuestionId = "q-8"
                        },
                        new
                        {
                            Id = "a-91",
                            AnswerDescription = "Mercury",
                            AnswerNumber = 1,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6642),
                            IsCorrect = true,
                            QuestionId = "q-9"
                        },
                        new
                        {
                            Id = "a-92",
                            AnswerDescription = "Atlantic Ocean",
                            AnswerNumber = 2,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6645),
                            IsCorrect = false,
                            QuestionId = "q-9"
                        },
                        new
                        {
                            Id = "a-93",
                            AnswerDescription = "Indian Ocean",
                            AnswerNumber = 3,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6649),
                            IsCorrect = false,
                            QuestionId = "q-9"
                        },
                        new
                        {
                            Id = "a-94",
                            AnswerDescription = "Arctic Ocean",
                            AnswerNumber = 4,
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6652),
                            IsCorrect = false,
                            QuestionId = "q-9"
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CourseEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CourseStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "c-1",
                            CourseDescription = "This course provides an introduction to programming concepts using a variety of languages.",
                            CourseEndingDate = new DateTime(2024, 7, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6894),
                            CourseName = "Introduction to Programming",
                            CourseStartingDate = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6892),
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6875)
                        },
                        new
                        {
                            Id = "c-2",
                            CourseDescription = "This course provides an introduction to programming concepts using a variety of languages.",
                            CourseEndingDate = new DateTime(2024, 7, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6912),
                            CourseName = "Introduction to Programming 2",
                            CourseStartingDate = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6910),
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6907)
                        },
                        new
                        {
                            Id = "c-3",
                            CourseDescription = "This course provides an introduction to programming concepts using a variety of languages.",
                            CourseEndingDate = new DateTime(2024, 7, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6919),
                            CourseName = "Introduction to Programming 3",
                            CourseStartingDate = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6917),
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6915)
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Exam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExamDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<float?>("ExamGradeAvg")
                        .HasColumnType("real");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsOrderQuestionsRandom")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartExamDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = "e-1",
                            CourseId = "c-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6961),
                            ExamDescription = "Description of Midterm Exam",
                            ExamDurationInMinutes = 120,
                            ExamGradeAvg = 0f,
                            ExamName = "Midterm Exam",
                            IsOrderQuestionsRandom = true,
                            StartExamDateTime = new DateTime(2024, 4, 11, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6970),
                            TeacherId = "t-1",
                            TeacherName = "John Doe"
                        },
                        new
                        {
                            Id = "e-2",
                            CourseId = "c-2",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6979),
                            ExamDescription = "Description of Final Exam",
                            ExamDurationInMinutes = 180,
                            ExamGradeAvg = 0f,
                            ExamName = "Final Exam",
                            IsOrderQuestionsRandom = true,
                            StartExamDateTime = new DateTime(2024, 4, 18, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6983),
                            TeacherId = "t-1",
                            TeacherName = "John Doe"
                        },
                        new
                        {
                            Id = "e-3",
                            CourseId = "c-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6987),
                            ExamDescription = "Description of Quiz 1",
                            ExamDurationInMinutes = 60,
                            ExamGradeAvg = 0f,
                            ExamName = "Quiz 1",
                            IsOrderQuestionsRandom = false,
                            StartExamDateTime = new DateTime(2024, 4, 25, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(6989),
                            TeacherId = "t-1",
                            TeacherName = "John Doe"
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsOrderAnswersRandom")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<int>("QuestionScoring")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = "q-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7030),
                            ExamId = "e-1",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of the United Kingdom?",
                            QuestionNumber = 1,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-2",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7109),
                            ExamId = "e-1",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of Germany?",
                            QuestionNumber = 2,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-3",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7116),
                            ExamId = "e-1",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of Italy?",
                            QuestionNumber = 3,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-4",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7125),
                            ExamId = "e-2",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of the United Kingdom?",
                            QuestionNumber = 1,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-5",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7131),
                            ExamId = "e-2",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of Germany?",
                            QuestionNumber = 2,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-6",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7135),
                            ExamId = "e-2",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the capital of Italy?",
                            QuestionNumber = 3,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-7",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7139),
                            ExamId = "e-3",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the largest ocean on Earth?",
                            QuestionNumber = 1,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-8",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7143),
                            ExamId = "e-3",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "Which planet is known as the Red Planet?",
                            QuestionNumber = 2,
                            QuestionScoring = 1
                        },
                        new
                        {
                            Id = "q-9",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7147),
                            ExamId = "e-3",
                            IsOrderAnswersRandom = true,
                            QuestionDescription = "What is the chemical symbol for water?",
                            QuestionNumber = 3,
                            QuestionScoring = 1
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.QuestionFailed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChosenWrongAnswerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChosenWrongAnswerNumber")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectAnswerNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<int>("QuestionScoring")
                        .HasColumnType("int");

                    b.Property<string>("StudentExamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentExamId");

                    b.ToTable("QuestionsFailed");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.StudentExam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExamStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("WasExamLoggedInToByStudent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentsExams");

                    b.HasData(
                        new
                        {
                            Id = "se-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7203),
                            ExamId = "e-1",
                            Grade = 90,
                            StudentId = "s-1",
                            StudentName = "Alice Smith",
                            WasExamLoggedInToByStudent = true
                        },
                        new
                        {
                            Id = "se-2",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7211),
                            ExamId = "e-2",
                            Grade = 85,
                            StudentId = "s-2",
                            StudentName = "Alice Smith",
                            WasExamLoggedInToByStudent = true
                        },
                        new
                        {
                            Id = "se-3",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7218),
                            ExamId = "e-3",
                            Grade = 95,
                            StudentId = "s-2",
                            StudentName = "Rifka Smith",
                            WasExamLoggedInToByStudent = true
                        },
                        new
                        {
                            Id = "se-4",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7222),
                            ExamId = "e-1",
                            Grade = 80,
                            StudentId = "s-2",
                            StudentName = "Rifka Smith",
                            WasExamLoggedInToByStudent = true
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("StudentGradeAvg")
                        .HasColumnType("real");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "a-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 711, DateTimeKind.Local).AddTicks(7264),
                            Email = "leahwalden4@gmail.com",
                            FullName = "The Admin",
                            PasswordHash = "$2a$10$qdPpxmTjjIEQqL/30f8.m.PcKhaHH5UGlPO0eUJhExNam1FXms0BO",
                            UserName = "admin",
                            UserRole = "Admin"
                        },
                        new
                        {
                            Id = "t-1",
                            CourseId = "c-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 795, DateTimeKind.Local).AddTicks(2700),
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            PasswordHash = "$2a$10$b3oS5wS.uD2IIABZPIfYYuM5KpWL00T.XFZ3FgfXBpZghbQaUtorC",
                            UserName = "teacher1",
                            UserRole = "Teacher"
                        },
                        new
                        {
                            Id = "s-1",
                            CourseId = "c-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 885, DateTimeKind.Local).AddTicks(8715),
                            Email = "alice.smith@example.com",
                            FullName = "Alice Smith",
                            PasswordHash = "$2a$10$zzeXWOcjZ72uc9U2e6ZpNO1Q7VJ8fpFcf10.qaV4stuh/Kx5Ftlz2",
                            StudentGradeAvg = 0f,
                            UserName = "student1",
                            UserRole = "Student"
                        },
                        new
                        {
                            Id = "s-2",
                            CourseId = "c-1",
                            CreatedAt = new DateTime(2024, 4, 4, 17, 4, 55, 986, DateTimeKind.Local).AddTicks(9982),
                            Email = "rifka.smith@example.com",
                            FullName = "Rifka Smith",
                            PasswordHash = "$2a$10$gQ39tNx74SJC/o66S81wl.ysGB6chi6WMQJxBmIxDp9eXIN05YMZq",
                            StudentGradeAvg = 0f,
                            UserName = "student2",
                            UserRole = "Student"
                        });
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Answer", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Exam", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.Course", null)
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.User", null)
                        .WithMany("TeachersExams")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Question", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.Exam", null)
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.QuestionFailed", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.StudentExam", null)
                        .WithMany("QuestionsFailed")
                        .HasForeignKey("StudentExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.StudentExam", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.Exam", null)
                        .WithMany("StudentsExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.User", null)
                        .WithMany("StudentsTakenExams")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.User", b =>
                {
                    b.HasOne("Exams_App_C__.Net_Server.Data.Models.Course", null)
                        .WithMany("Users")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Course", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("StudentsExams");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.StudentExam", b =>
                {
                    b.Navigation("QuestionsFailed");
                });

            modelBuilder.Entity("Exams_App_C__.Net_Server.Data.Models.User", b =>
                {
                    b.Navigation("StudentsTakenExams");

                    b.Navigation("TeachersExams");
                });
#pragma warning restore 612, 618
        }
    }
}
